server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: testserver-db2.cw9han1hpszg.ap-northeast-2.rds.amazonaws.com
    username: master
    password: parkjh9194
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전